### ISSUE TITLE
Head Component bug – Tailwind: To use responsive styles you must have a <head> element as a direct child of the Tailwind component.

### ISSUE THREAD

**Issue by laurisbernhart** [resend/react-email#1112]
### Describe the Bug

First, thanks for improving the email DX so much with this library🙌

When using the Head component as a direct child of Tailwind:

If NODE_ENV is set to production, I receive the following error:

_Tailwind: To use responsive styles you must have a <head> element as a direct child of the Tailwind component._

If NODE_ENV is set to development, it will work as expected.

**Does not work in production:**

`
  <Tailwind
      config={...}
    >
      <Head>
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
      </Head>
     ...
     </Tailwind>
 `

**Workaround**
Using a normal head tag works when NODE_ENV is set to production too.

    `<Tailwind
      config={...}
    >
      <head>
        <meta content="text/html; charset=UTF-8" httpEquiv="Content-Type" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
      </head>
...
      </Html>
    </Tailwind>`
    
    
 Without digging deeper and trying it out, my best guess is that this check fails in production https://github.com/resend/react-email/blob/778f3b08610f8432aaa90a7d8a46faa8e08bcc67/packages/tailwind/src/tailwind.tsx#L181C17-L181C18

Best Lauris

### Link to the code that reproduces this issue

-

### To Reproduce

-

### Expected Behavior

-

### What's your node version? (if relevant)

v18.16.0

**Comment by gabrielmfern** [comment]
Can you give a reproduction for this issue?

**Comment by gabrielmfern** [comment]
Really can't reproduce this issue, could any of you give a minimal reproduction @xonx4l @laurisbernhart?

**Comment by zegl** [comment]
Hi, I have been running into the same issue, and have created [a minimal reproduction](https://github.com/zegl/react-email-tailwind).

It's a NextJS project, where react-email works in dev-mode (`npm run dev`), but not in the production build (`npm run build`).

In dev-mode, you can see that the response renders fine at http://localhost:3000/email-media.

However, when building for production, it fails:

```
Error occurred prerendering page "/email-media". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Tailwind: To use responsive styles you must have a <head> element as a direct child of the Tailwind component.
    at kF (~/react-email-tailwind/.next/server/chunks/387.js:2409:1881)
    at tY (~/react-email-tailwind/.next/server/chunks/387.js:21:186500)
    at tJ (~/react-email-tailwind/.next/server/chunks/387.js:21:203279)
    at tZ (~/react-email-tailwind/.next/server/chunks/387.js:21:205933)
    at tY (~/react-email-tailwind/.next/server/chunks/387.js:21:197643)
    at tJ (~/react-email-tailwind/.next/server/chunks/387.js:21:203279)
    at tK (~/react-email-tailwind/.next/server/chunks/387.js:21:186055)
    at tY (~/react-email-tailwind/.next/server/chunks/387.js:21:186651)
    at tJ (~/react-email-tailwind/.next/server/chunks/387.js:21:203279)
    at t8 (~/react-email-tailwind/.next/server/chunks/387.js:21:210435)
```

Using `@react-email/tailwind` `0.0.13`.

**Comment by juliuslipp** [comment]
As a temporary workaround you can downgrade to `@react-email/tailwind 0.0.12`. Was facing the same issue.

**Comment by gabrielmfern** [comment]
Thanks @zegl for the repro, I'll look into this right now. The issue is probably because we check for either the `head` element or a function component with the name `Head` and since minifcation changes this it causes the issue.

**Comment by gabrielmfern** [comment]
@zegl Would you consider checking this plugin out https://www.npmjs.com/package/webpack-react-component-name? I think using it can be a workaround on this for now and it may confirm my suspicion for what is causing the issue here.

**Comment by zegl** [comment]
@gabrielmfern I tried, but I haven't been able to get it to work with the `webpack-react-component-name` plugin. But you're probably on the right track, it sounds likely that some magnification would break the names of custom components.

**Comment by antoinerousseau** [comment]
Same here, this bug makes it impossible to use Tailwind responsive classes. The workaround does not work since it does not allow the Tailwind component to inject its styles into the <head>.

**Comment by mucahidyazar** [comment]
I installed just `@react-email/components` to my CRA dashboard project and I was facing the same issue and fixed it like below. It is a workaround. But there is still an issue like this. 

![image](https://github.com/resend/react-email/assets/52811808/de26f8ae-b29b-4afd-abc4-e9fdb43011cd)

**Comment by gabrielmfern** [comment]
A better temporary workaround is to use the <head> element substituting the <Head> component for now. If you want the same exact code and behavior as the <Head> component gives, you can get its code here:

https://github.com/resend/react-email/blob/bb8cd54a504ed09f562c4d14ada2241dfb35a2be/packages/head/src/head.tsx#L8-L11

Haven't fixed this quite yet because of #1124.

**Comment by gabrielmfern** [comment]
Fixed and released under `@react-email/tailwind@0.0.15-canary.1`. See the release notes on https://github.com/resend/react-email/releases/tag/%40react-email%2Ftailwind%400.0.15-canary.1.

If any of you still experience this issue, please let me know and I'll reopen.
