### ISSUE TITLE
option --dir dosn't  work for build command

### ISSUE THREAD

**Issue by Robin-Ln** [resend/react-email#1246]
### Describe the Bug

when i execute `email build --dir src/emails` i get this error : 

```
error: Could not resolve "/Users/rlouarn/git/programme-tz-2023/emails/previews/preview-magic-link-email.tsx"
```

for fix this issue i need to update the env variable `NEXT_PUBLIC_EMAILS_DIR_RELATIVE_PATH` in `.react-eamil/next.config.js`: 

```
-       NEXT_PUBLIC_EMAILS_DIR_RELATIVE_PATH: 'emails',
+      NEXT_PUBLIC_EMAILS_DIR_RELATIVE_PATH: 'src/emails',
```

### Link to the code that reproduces this issue

https://gitlab.com/robin.louarn/programme-tz-2023

### To Reproduce

nvm use
pnpm install
pnpm email:build

### Expected Behavior

generate a build correctly for deploy him on vercel

### What's your node version? (if relevant)

20.11.0

**Comment by Robin-Ln** [comment]
i think there are an other similar error, look this error : 

```
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at h (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/chunks/766.js:1:4078)
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at h (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/chunks/766.js:1:4078)
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at h (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/chunks/766.js:1:4078)
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at h (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/chunks/766.js:1:4078)

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at h (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/chunks/766.js:1:4078)
   Generating static pages (4/6) 

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at h (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/chunks/766.js:1:4078)
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at d (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/app/preview/[slug]/page.js:1:95842)
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at h (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/chunks/766.js:1:4078)
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at d (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/app/preview/[slug]/page.js:1:95842)
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
    at h (/Users/rlouarn/git/programme-tz-2023/.react-email/.next/server/chunks/766.js:1:4078)

Error occurred prerendering page "/preview/magic-link-email.tsx". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Could not find the emails directory specified under /Users/rlouarn/git/programme-tz-2023/emails!
```

my command is : 

```
...
    "email:build": "email build --dir src/emails",
...
```

**Comment by gabrielmfern** [comment]
Hey @Robin-Ln, could you open up another issue for that?
