### ISSUE TITLE
email preview complains about missing dependencies

### ISSUE THREAD

**Issue by kuro610** [resend/react-email#1251]
### Describe the Bug

When I run the email dev command and go to the email preview open an email I get an error message that some dependencies could not be resolved. But these dependencies are installed in the project.

Error: Build failed with 14 errors:
../lib/measurements.ts:1:35: ERROR: Could not resolve "luxon"
../lib/orgUnits.ts:1:18: ERROR: Could not resolve "zod"
../lib/periodic.ts:1:18: ERROR: Could not resolve "zod"
../lib/periodic.ts:3:25: ERROR: Could not resolve "luxon"
../lib/reinigungsTaskDef.ts:1:30: ERROR: Could not resolve "xstate"
...
    at failureErrorWithLog (/project/backend/node_modules/react-email/node_modules/esbuild/lib/main.js:1651:15)
    at /project/node_modules/react-email/node_modules/esbuild/lib/main.js:1059:25
    at /project/node_modules/react-email/node_modules/esbuild/lib/main.js:1004:52
    at buildResponseToResult (/project/node_modules/react-email/node_modules/esbuild/lib/main.js:1057:7)
    at /project/node_modules/react-email/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/project/node_modules/react-email/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/project/node_modules/react-email/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/project/node_modules/react-email/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)

I'm using version 2.0.0.

### Link to the code that reproduces this issue

-

### To Reproduce

Typing email props with types which are imported from another file which have external dependencies.

### Expected Behavior

The external dependencies should be found.

### What's your node version? (if relevant)

20.11.0

**Comment by gabrielmfern** [comment]
Could you make a reproduction of this?

**Comment by kuro610** [comment]
Here is a minimal reproduction of the error:

[Repo](https://github.com/kuro610/react-email-error)

**Comment by gabrielmfern** [comment]
@kuro610 I was able to get no error by moving the package.json up in the project or moving the lib directory down.

We use esbuild under the hood to bundle in all the dependencies for the email so in the same way esbuild can't figure
out the dependencies properly we can't either. This can probably be fixed by either moving the file inside of where the `package.json` is, or moving the `pacakge.json` to the root.
