### ISSUE TITLE
ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by oga-sven** [resend/react-email#1255]
### Describe the Bug

New install. Used automatic setup. 
`npx create-email@latest`
then 
`npm i`
then 
`npm run dev`

I end up getting this error below:

```
ReferenceError: Request is not defined
    at Object.<anonymous> (Z:\projects\etc\react-email-starter\node_modules\next\dist\server\web\spec-extension\request.js:28:27)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.mod.require (Z:\projects\etc\react-email-starter\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (Z:\projects\etc\react-email-starter\node_modules\next\dist\server\web\spec-extension\adapters\next-request.js:37:18)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.mod.require (Z:\projects\etc\react-email-starter\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/cjs/helpers:102:18)

shutting down dev server
```

when opening the affected file in my IDE, `Request` is completely fine. I am using windows 10

>node -v
v17.0.1

>npm -v
8.1.0

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

Fresh install

### To Reproduce

See above, essentially,  its just a fresh install

### Expected Behavior

For the dev server to start after a fresh install

### What's your node version? (if relevant)

v17.0.1

**Comment by oga-sven** [comment]
note: same result if i follow the manual instructions from https://react.email/docs/getting-started/manual-setup

**Comment by edenstrom** [comment]
Upgrade Node.js to at least 18.x which introduces the `fetch` API and the `Request` global. 17.x went EOL in 2022.

Support also exists behind a flag in 17.5+ but that's still EOL.

**Comment by oga-sven** [comment]
Thanks! I was not aware the fetch api wasnt present pre v18
