### ISSUE TITLE
Default create-email boilerplate : Nextjs app crash at startup

### ISSUE THREAD

**Issue by FaureAlexis** [resend/react-email#1278]
### Describe the Bug

Hey there,
just created a new react-email project using : `npx create-email@latest` and when I run `email dev` I got the following error : 
![image](https://github.com/resend/react-email/assets/75880156/73c2fbbb-308d-491b-8afd-4056275f70ab)

```
 ⨯ TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:1172:7)
    at eval (./src/actions/get-emails-directory-metadata.ts:53:116)
    at Array.filter (<anonymous>)
    at getEmailsDirectoryMetadata (./src/actions/get-emails-directory-metadata.ts:53:36)
    at async RootLayout (./src/app/layout.tsx:23:37)
```

I finally got it running by adding this code to the next app, under `src/actions/get-emails-directory-metadata.ts` : 
```typescript
export const getEmailsDirectoryMetadata = async (
  absolutePathToEmailsDirectory: string,
): Promise<EmailsDirectory | undefined> => {
  if (!fs.existsSync(absolutePathToEmailsDirectory)) return;

  const dirents = await fs.promises.readdir(absolutePathToEmailsDirectory, {
    withFileTypes: true,
  });

/** added the code below : */
  dirents.forEach((dirent) => {
    dirent.path = absolutePathToEmailsDirectory;
  });

  const emailFilenames = dirents
    .filter((dirent) => isFileAnEmail(path.join(dirent.path, dirent.name)))
    .map((dirent) => dirent.name);
...
```
Idk if the issue is related to my env or not, let me know so I could open a PR or not.

Ty 

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

just run `npx create-email@latest` and start app

### To Reproduce

just run `npx create-email@latest` and start app

### Expected Behavior

Default app should start :) 

### What's your node version? (if relevant)

tried with 18 and 20

**Comment by gabrielmfern** [comment]
closing as a duplicate of #1235

**Comment by gabrielmfern** [comment]
Making this change might not be the most stable way here, a better workaround would be upgrading Node temporarily as mentioned in #1235.

**Comment by FaureAlexis** [comment]
Thanks you, appreciate your help.
