### ISSUE TITLE
Build fails on Mac Silicon chips

### ISSUE THREAD

**Issue by vanvilecks-not-dead** [resend/react-email#1582]
### Describe the Bug

Running email dev or email export commands produce errors such as Could not resolve "@react-email/components" and similar messages indicating that dependencies cannot be resolved, although they are present. More details can be seen in the stack trace below.

The issue occurs with any version of react-email and any version of Node.js.

However, if npm run dev is executed in GitHub Workspaces or on a Linux distribution with x86 architecture, everything works as expected. The same example that fails on Mac works correctly in these environments.

**stack-trace:**

```sh 

Error: Build failed with 2 errors: emails/vercel-invite-user.tsx:17:7: ERROR: Could not resolve "@react-email/components" emails/vercel-invite-user.tsx:51:6: ERROR: Could not resolve "react/jsx-runtime"
Error: Build failed with 2 errors:
emails/vercel-invite-user.tsx:17:7: ERROR: Could not resolve "@react-email/components"
emails/vercel-invite-user.tsx:51:6: ERROR: Could not resolve "react/jsx-runtime"
    at failureErrorWithLog (/Users/vanvilecks/react-email-turborepo-npm-example/node_modules/react-email/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/vanvilecks/react-email-turborepo-npm-example/node_modules/react-email/node_modules/esbuild/lib/main.js:1059:25
    at /Users/vanvilecks/react-email-turborepo-npm-example/node_modules/react-email/node_modules/esbuild/lib/main.js:1004:52
    at buildResponseToResult (/Users/vanvilecks/react-email-turborepo-npm-example/node_modules/react-email/node_modules/esbuild/lib/main.js:1057:7)
    at /Users/vanvilecks/react-email-turborepo-npm-example/node_modules/react-email/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/Users/vanvilecks/react-email-turborepo-npm-example/node_modules/react-email/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/Users/vanvilecks/react-email-turborepo-npm-example/node_modules/react-email/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/Users/vanvilecks/react-email-turborepo-npm-example/node_modules/react-email/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)

```

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/resend/react-email-turborepo-npm-example

### To Reproduce

On a Mac with a Silicon chip, clone the react-email repository.

1. Run npm install to install dependencies.
2. Execute the email dev or email export command.
3. Observe the errors related to unresolved dependencies.

### Expected Behavior

The build should succeed without errors on Mac Silicon chips, resolving all dependencies correctly as it does in GitHub Workspaces or on x86 Linux distributions.

### What's your node version? (if relevant)

22.2.0

**Comment by gabrielmfern** [comment]
Are you sure this isn't the same as mentioned [here in Discord](https://discord.com/channels/1022242959736983613/1219724322323824712/1219744752669294692)?

![image](https://github.com/user-attachments/assets/9e928143-298b-4325-ad1b-55f4a8471bf8)

**Comment by vanvilecks-not-dead** [comment]
@gabrielmfern Thank you! That really helped and now everything works as it should 🥇

**Comment by vanvilecks-not-dead** [comment]
@gabrielmfern Thank you! That really helped and now everything works as it should 🥇
