### ISSUE TITLE
RSC error when using tailwind component

### ISSUE THREAD

**Issue by realmers** [resend/react-email#968]
### Describe the Bug

When trying to render the following react email component with pnpm email dev.
```tsx
import * as React from "react";
import { Html } from "@react-email/html";
import { Tailwind } from "@react-email/tailwind";

interface form {
	to?: string;
	from?: string;
	name: string;
	subject: string;
	email: string;
	mobilenumber: string;
	message: string;
}

export default function Email(ContactForm: form) {
	const { name, subject, email, mobilenumber, message } = ContactForm;
	return (
		<Html lang="sv">
			<Tailwind >
				<p className="pb-4">{message}</p>
			</Tailwind>
		</Html>
	);
}
```

I get the following error stack:
```
../node_modules/.pnpm/@react-email+tailwind@0.0.9/node_modules/@react-email/tailwind/dist/index.mjs
  Error: 
    x NEXT_RSC_ERR_SERVER_IMPORT: react-dom/server
      ,-[C:\Users\danho\Desktop\robertsfoto\node_modules\.pnpm\@react-email+tailwind@0.0.9\node_modules\@react-email\tailwind\dist\index.mjs:20:1]
   20 | 
   21 | // src/tailwind.tsx
   22 | import * as React from "react";
   23 | import { renderToStaticMarkup } from "react-dom/server";
      : ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   24 | import htmlParser, {
   25 |   attributesToProps,
   26 |   domToReact,
```

Everything works and previews fine without the Tailwind component but not with it attached.

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

https://github.com/realmers/robertsfoto/tree/eccomerce

### To Reproduce

1. download the repo highlited above
2. run pnpm emailDev
3. navigate to the only mail available for preview
4. fails to compile and error above appears

### Expected Behavior

Email should be previewable

### What's your node version? (if relevant)

v18.17.1

**Comment by Soliux** [comment]
Yeah, same thing is happening to me when I try to use the Tailwind component and use custom classes.

I took the example straight from the docs and the error persists.

**Comment by 220ish** [comment]
+1, same error with server components in nextjs v13

**Comment by rainstorm-studio-australia** [comment]
Downgrade it to v.0.0.8 works for me: `npm i @react-email/tailwind@^0.0.8`

**Comment by bukinoshita** [comment]
Does this still happens with the latest version?

**Comment by voinik** [comment]
@bukinoshita I'm still getting a similar error. I've tried using `@react-email/tailwind@0.0.8`, `@react-email/tailwind@0.0.12` and `@react-email/tailwind@0.0.13-canary.0`, but they all cause the below error:

>Internal error: Error: Internal Error: do not use legacy react-dom/server APIs. If you encountered this error, please open an issue on the Next.js repo.
    at renderToStaticMarkup (./node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/build/noop-react-dom-server-legacy.js:11:11)
    at Tailwind (./node_modules/.pnpm/@react-email+tailwind@0.0.13-canary.0_react@18.2.0/node_modules/@react-email/tailwind/dist/index.mjs:174:92)
    at renderWithHooks (./node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:4831:26)
    at renderIndeterminateComponent (./node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:4889:25)
    at renderElement (./node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5064:21)
    at renderNodeDestructiveImpl (./node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5196:29)
    at renderNodeDestructive (./node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5172:28)
    at renderNode (./node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5320:24)
    at renderChildrenArray (./node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5282:21)
    at renderNodeDestructiveImpl (./node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5227:21)

I assume it's because we're importing 
```ts
import { renderToStaticMarkup } from "react-dom/server";
```
in the `Tailwind` component.

Any ideas on what would be a good replacement for `renderToStaticMarkup`?

**Comment by gobielJonathan** [comment]
Yeah, same thing is happening to me when I try to use the Tailwind component and use custom classes.

I took the example straight from the docs and the error persists.

**Comment by 220ish** [comment]
the error is still there^

**Comment by gabrielmfern** [comment]
As of `@react-email/tailwind@0.0.14` this should be fixed.

Check the changelog for more info https://react.email/docs/changelog#jan-16-2024
